unstable_features = true

indent_style = "Block"
reorder_imports = true
binop_separator = "Back"
# force_multiline_blocks = true
overflow_delimited_expr = true

hard_tabs = true

brace_style = "PreferSameLine"

enum_discrim_align_threshold = 10
struct_field_align_threshold = 10

imports_layout = "HorizontalVertical"

reorder_impl_items = true

group_imports = "StdExternalCrate"

max_width = 110
fn_call_width=80
attr_fn_like_width=70
struct_lit_width=18
struct_variant_width=35
array_width=60
chain_width=80
single_line_if_else_max_width=50

imports_granularity = "Module"

edition = "2021"